python .\BinToMem_CLI.py .\TestBin\addi-riscv64-mycpu.bin  .\TestBin\bin\addi-riscv64-mycpu.txt 8
python .\BinToMem_CLI.py .\TestBin\addiw-riscv64-mycpu.bin .\TestBin\bin\addiw-riscv64-mycpu.txt 8
python .\BinToMem_CLI.py .\TestBin\add-riscv64-mycpu.bin .\TestBin\bin\add-riscv64-mycpu.txt 8
python .\BinToMem_CLI.py .\TestBin\addw-riscv64-mycpu.bin .\TestBin\bin\addw-riscv64-mycpu.txt 8
python .\BinToMem_CLI.py .\TestBin\andi-riscv64-mycpu.bin .\TestBin\bin\andi-riscv64-mycpu.txt 8
python .\BinToMem_CLI.py .\TestBin\and-riscv64-mycpu.bin .\TestBin\bin\and-riscv64-mycpu.txt 8
python .\BinToMem_CLI.py .\TestBin\auipc-riscv64-mycpu.bin .\TestBin\bin\auipc-riscv64-mycpu.txt 8
python .\BinToMem_CLI.py .\TestBin\beq-riscv64-mycpu.bin .\TestBin\bin\beq-riscv64-mycpu.txt 8
python .\BinToMem_CLI.py .\TestBin\bge-riscv64-mycpu.bin .\TestBin\bin\bge-riscv64-mycpu.txt 8
python .\BinToMem_CLI.py .\TestBin\bgeu-riscv64-mycpu.bin .\TestBin\bin\bgeu-riscv64-mycpu.txt 8
python .\BinToMem_CLI.py .\TestBin\blt-riscv64-mycpu.bin .\TestBin\bin\blt-riscv64-mycpu.txt 8
python .\BinToMem_CLI.py .\TestBin\bltu-riscv64-mycpu.bin .\TestBin\bin\bltu-riscv64-mycpu.txt 8
python .\BinToMem_CLI.py .\TestBin\bne-riscv64-mycpu.bin .\TestBin\bin\bne-riscv64-mycpu.txt 8
python .\BinToMem_CLI.py .\TestBin\jal-riscv64-mycpu.bin .\TestBin\bin\jal-riscv64-mycpu.txt 8
python .\BinToMem_CLI.py .\TestBin\jalr-riscv64-mycpu.bin .\TestBin\bin\jalr-riscv64-mycpu.txt 8
python .\BinToMem_CLI.py .\TestBin\lb-riscv64-mycpu.bin .\TestBin\bin\lb-riscv64-mycpu.txt 8
python .\BinToMem_CLI.py .\TestBin\lbu-riscv64-mycpu.bin .\TestBin\bin\lbu-riscv64-mycpu.txt 8
python .\BinToMem_CLI.py .\TestBin\lh-riscv64-mycpu.bin .\TestBin\bin\lh-riscv64-mycpu.txt 8
python .\BinToMem_CLI.py .\TestBin\lhu-riscv64-mycpu.bin .\TestBin\bin\lhu-riscv64-mycpu.txt 8
python .\BinToMem_CLI.py .\TestBin\lw-riscv64-mycpu.bin .\TestBin\bin\lw-riscv64-mycpu.txt 8
python .\BinToMem_CLI.py .\TestBin\lwu-riscv64-mycpu.bin .\TestBin\bin\lwu-riscv64-mycpu.txt 8
python .\BinToMem_CLI.py .\TestBin\ld-riscv64-mycpu.bin .\TestBin\bin\ld-riscv64-mycpu.txt 8
python .\BinToMem_CLI.py .\TestBin\lui-riscv64-mycpu.bin .\TestBin\bin\lui-riscv64-mycpu.txt 8
python .\BinToMem_CLI.py .\TestBin\ori-riscv64-mycpu.bin .\TestBin\bin\ori-riscv64-mycpu.txt 8
python .\BinToMem_CLI.py .\TestBin\or-riscv64-mycpu.bin .\TestBin\bin\or-riscv64-mycpu.txt 8
python .\BinToMem_CLI.py .\TestBin\sb-riscv64-mycpu.bin .\TestBin\bin\sb-riscv64-mycpu.txt 8
python .\BinToMem_CLI.py .\TestBin\sh-riscv64-mycpu.bin .\TestBin\bin\sh-riscv64-mycpu.txt 8
python .\BinToMem_CLI.py .\TestBin\sw-riscv64-mycpu.bin .\TestBin\bin\sw-riscv64-mycpu.txt 8
python .\BinToMem_CLI.py .\TestBin\sd-riscv64-mycpu.bin .\TestBin\bin\sd-riscv64-mycpu.txt 8
python .\BinToMem_CLI.py .\TestBin\slli-riscv64-mycpu.bin .\TestBin\bin\slli-riscv64-mycpu.txt 8
python .\BinToMem_CLI.py .\TestBin\slliw-riscv64-mycpu.bin .\TestBin\bin\slliw-riscv64-mycpu.txt 8
python .\BinToMem_CLI.py .\TestBin\sll-riscv64-mycpu.bin .\TestBin\bin\sll-riscv64-mycpu.txt 8
python .\BinToMem_CLI.py .\TestBin\sllw-riscv64-mycpu.bin .\TestBin\bin\sllw-riscv64-mycpu.txt 8
python .\BinToMem_CLI.py .\TestBin\slti-riscv64-mycpu.bin .\TestBin\bin\slti-riscv64-mycpu.txt 8
python .\BinToMem_CLI.py .\TestBin\sltiu-riscv64-mycpu.bin .\TestBin\bin\sltiu-riscv64-mycpu.txt 8
python .\BinToMem_CLI.py .\TestBin\slt-riscv64-mycpu.bin .\TestBin\bin\slt-riscv64-mycpu.txt 8
python .\BinToMem_CLI.py .\TestBin\sltu-riscv64-mycpu.bin .\TestBin\bin\sltu-riscv64-mycpu.txt 8
python .\BinToMem_CLI.py .\TestBin\srai-riscv64-mycpu.bin .\TestBin\bin\srai-riscv64-mycpu.txt 8
python .\BinToMem_CLI.py .\TestBin\sraiw-riscv64-mycpu.bin .\TestBin\bin\sraiw-riscv64-mycpu.txt 8
python .\BinToMem_CLI.py .\TestBin\sra-riscv64-mycpu.bin .\TestBin\bin\sra-riscv64-mycpu.txt 8
python .\BinToMem_CLI.py .\TestBin\sraw-riscv64-mycpu.bin .\TestBin\bin\sraw-riscv64-mycpu.txt 8
python .\BinToMem_CLI.py .\TestBin\srli-riscv64-mycpu.bin .\TestBin\bin\srli-riscv64-mycpu.txt 8
python .\BinToMem_CLI.py .\TestBin\srliw-riscv64-mycpu.bin .\TestBin\bin\srliw-riscv64-mycpu.txt 8
python .\BinToMem_CLI.py .\TestBin\srl-riscv64-mycpu.bin .\TestBin\bin\srl-riscv64-mycpu.txt 8
python .\BinToMem_CLI.py .\TestBin\srlw-riscv64-mycpu.bin .\TestBin\bin\srlw-riscv64-mycpu.txt 8
python .\BinToMem_CLI.py .\TestBin\xori-riscv64-mycpu.bin .\TestBin\bin\xori-riscv64-mycpu.txt 8
python .\BinToMem_CLI.py .\TestBin\xor-riscv64-mycpu.bin .\TestBin\bin\xor-riscv64-mycpu.txt 8